Fix some addtional errors in NCZarr
Unidata/netcdf-c pull request #2503
Opened 2022-09-09 20:26 UTC by DennisHeimbigner

re: Issue https://github.com/Unidata/netcdf-c/issues/2502

H/T Charlie Zender

* Fix NCZarr handling of endianness value NC_ENDIAN_NATIVE. This now matches how it is handled in libhdf5
* Fix NCZarr handling of char typed attribute with value "". This now matches how it is handled in libhdf5
* Add test for various char attribute values
* Change the mapping of NC_CHAR and NC_STRING to dtype; requires changing some test files also.
* Optimize the testing for NC_ENOTBUILT in NC_open.
* Turn off debugging left on accidentally
* Fix memory leak in tst_pnetcdf.c
* Fix blosc test

2022-09-09 22:44 UTC, WardF requested changes

2022-09-09 22:44 UTC, WardF commented on RELEASE_NOTES.md
> +* [Bug Fix] Fix some errors detected in Follow on to PR 2497. [PR #2497](https://github.com/Unidata/netcdf-c/pull/2497) . See [Github #????](https://github.com/Unidata/netcdf-c/pull/????).
@DennisHeimbigner can you fill in the `????`, or let me know what the correct number should be for this string?

2022-09-13 08:39 UTC, czender commented
@DennisHeimbigner and @WardF Once the PR is merged I will test and possibly demonstrate some of the new netCDF lossy compression features on Zarr files here (with @ethanrd) at the CF meeting in Santander. My talk is mañana...

2022-09-14 20:25 UTC, WardF approved these changes

2022-09-14 20:25 UTC, WardF commented
Thanks @DennisHeimbigner !

2022-09-14 20:26 UTC, merged