[S3] Parse AWS configuration with support for profile section
Unidata/netcdf-c pull request #2969
Opened 2024-08-08 11:01 UTC by mannreis

Hello :wave:!

I've faced a **minor problem** on my setup when I have a profile section on the configuration file [1] (valid with aws tools). In such case the netcdf library fails to load the AWS config, not critical but not obvious.

This is a quick fix I did for my myself, but looking at the parser and aws config [specification](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html) I see parsing problems with:
 - Token delimiter characters in the values
 - Support for comments 
 - Multiline service configuration
 
I'm not sure to which extend you want to support loading the AWS config when the building with the internal S3 implementation.

Thanks!

[1]
`~/.aws/credentials`
```
[default]
aws_access_key_id=123
aws_secret_access_key=456

[user1]
aws_access_key_id=123
aws_secret_access_key=789
```

`~/.aws/config`
```
[default]
region=us-west-2
output=json

[profile user1]
region=us-east-1
output=text
```

2024-08-08 16:29 UTC, DennisHeimbigner commented
Let me make sure I understand.
1. When the profile name is specified as e.g "[user1]", the file (either credentials and config) parse correctly.
2. When the profile name is specified as e.g "[profile user1]", the file (either credentials and config) does not parse.

Have I stated the problem correctly?

2024-08-09 06:25 UTC, mannreis commented
Exactly!

2024-08-09 18:45 UTC, DennisHeimbigner commented on unit_test/run_aws_config.sh
It is probably best to not use the "env" command. Since each use overwrites AWS_PROFILE,
it is ok to just modify the value in-line.

2024-08-13 08:48 UTC, mannreis commented on unit_test/run_aws_config.sh
Thank you for reviewing!

2024-08-13 18:29 UTC, DennisHeimbigner requested changes
The best way to create a file in bash/sh is to use this method:
> https://jinnabaalu.medium.com/create-a-file-in-bash-using-eof-af5af33c0d1f

2024-08-19 17:32 UTC, WardF commented
Just checking in @DennisHeimbigner and @mannreis in regards to the latest changes requests.  It looks like @mannreis made some changes, how does this look now @DennisHeimbigner ?

2024-08-19 18:08 UTC, DennisHeimbigner requested changes
One more change, please. Remove the .aws directory at the end of the shell script so that automake distcheck will not fail.

2024-08-20 17:38 UTC, DennisHeimbigner approved these changes

2024-08-20 20:43 UTC, WardF approved these changes

2024-08-20 20:59 UTC, merged