fix ncuriparse error,Correctly remove leading and trailing whitespace
Unidata/netcdf-c pull request #2971
Opened 2024-08-10 06:49 UTC by ShawayL

fix ncuriparse error,Correctly remove leading and trailing whitespace.
When I use netcdf-c to connect to the nc file at the following path (D:/文档/test.nc), netcdf-c prompts me with a parameter error. After my investigation, I found that the error is caused by the ncuriparse function incorrectly interpreting the file path as a URI.

2024-08-10 06:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Unidata/netcdf-c?pullRequest=2971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Unidata/netcdf-c?pullRequest=2971) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Unidata/netcdf-c?pullRequest=2971) it.</sub>

2024-08-10 18:30 UTC, DennisHeimbigner requested changes
Shouldn't this line:
````    while(*(q - 1) == ' ' && (q - 1) >= uri) q--;````
be
````    while((q - 1) >= uri && *(q - 1) == ' ') q--;````

2024-08-11 01:18 UTC, ShawayL commented
> Shouldn't this line: be` while(*(q - 1) == ' ' && (q - 1) >= uri) q--;` ` while((q - 1) >= uri && *(q - 1) == ' ') q--;`

Thank you. I have fixed the issue.

2024-08-11 18:26 UTC, DennisHeimbigner approved these changes

2024-08-12 22:03 UTC, WardF approved these changes

2024-08-13 16:38 UTC, merged